/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as ApiContactFeedbackRouteImport } from './routes/api/contact-feedback'
import { Route as BooksBookIdReadRouteImport } from './routes/books.$bookId_.read'
import { Route as ApiPublicPodcastImportTickRouteImport } from './routes/api/public/podcast-import-tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/settings/agents',
  path: '/settings/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactFeedbackRoute = ApiContactFeedbackRouteImport.update({
  id: '/api/contact-feedback',
  path: '/api/contact-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdReadRoute = BooksBookIdReadRouteImport.update({
  id: '/books/$bookId_/read',
  path: '/books/$bookId/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPodcastImportTickRoute =
  ApiPublicPodcastImportTickRouteImport.update({
    id: '/api/public/podcast-import-tick',
    path: '/api/public/podcast-import-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/contact-feedback': typeof ApiContactFeedbackRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/podcast-import-tick': typeof ApiPublicPodcastImportTickRoute
  '/books/$bookId/read': typeof BooksBookIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/contact-feedback': typeof ApiContactFeedbackRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/books': typeof BooksIndexRoute
  '/api/public/podcast-import-tick': typeof ApiPublicPodcastImportTickRoute
  '/books/$bookId/read': typeof BooksBookIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/contact-feedback': typeof ApiContactFeedbackRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/podcast-import-tick': typeof ApiPublicPodcastImportTickRoute
  '/books/$bookId_/read': typeof BooksBookIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/contact-feedback'
    | '/books/$bookId'
    | '/join/$token'
    | '/settings/agents'
    | '/books/'
    | '/api/public/podcast-import-tick'
    | '/books/$bookId/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/contact-feedback'
    | '/books/$bookId'
    | '/join/$token'
    | '/settings/agents'
    | '/books'
    | '/api/public/podcast-import-tick'
    | '/books/$bookId/read'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/contact-feedback'
    | '/books/$bookId'
    | '/join/$token'
    | '/settings/agents'
    | '/books/'
    | '/api/public/podcast-import-tick'
    | '/books/$bookId_/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiContactFeedbackRoute: typeof ApiContactFeedbackRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ApiPublicPodcastImportTickRoute: typeof ApiPublicPodcastImportTickRoute
  BooksBookIdReadRoute: typeof BooksBookIdReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/settings/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-feedback': {
      id: '/api/contact-feedback'
      path: '/api/contact-feedback'
      fullPath: '/api/contact-feedback'
      preLoaderRoute: typeof ApiContactFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId_/read': {
      id: '/books/$bookId_/read'
      path: '/books/$bookId/read'
      fullPath: '/books/$bookId/read'
      preLoaderRoute: typeof BooksBookIdReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/podcast-import-tick': {
      id: '/api/public/podcast-import-tick'
      path: '/api/public/podcast-import-tick'
      fullPath: '/api/public/podcast-import-tick'
      preLoaderRoute: typeof ApiPublicPodcastImportTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiContactFeedbackRoute: ApiContactFeedbackRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  JoinTokenRoute: JoinTokenRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  BooksIndexRoute: BooksIndexRoute,
  ApiPublicPodcastImportTickRoute: ApiPublicPodcastImportTickRoute,
  BooksBookIdReadRoute: BooksBookIdReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
